apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.0
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: postgres-password
          - name: POSTGRES_DB
            value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=  # base64 encoded value for 'postgres'
  postgres-password: cG9zdGdyZXM=  # base64 encoded value for 'postgres'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 8
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: brunoangst/newskube:v3
          ports:
          - containerPort: 8080
          env:
          - name: DB_DATABASE
            value: postgres
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: postgres-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: postgres-password
          - name: DB_HOST
            value: postgres
          - name: AWS_ACCESS_KEY
            value: {{ AWS_ACCESS_KEY_ID }}
          - name: AWS_ACCESS_SECRET
            value: {{ AWS_SECRET_ACCESS_KEY }}
          - name: AWS_S3_BUCKET_NAME
            value: devops4devs-filesmbcangst
          - name: STORAGE_TYPE
            value: S3
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
