name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.1.2
      - name: Autenticando no Docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: "Construção da imagem Docher"
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            brunoangst/newskube:latest
            brunoangst/newskube:${{ github.run_number }}            
      - name: "Publicar a imagem no Docher Hub"
        run: echo "Docker push"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Configuração do ambuente AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: "Executar o deploy"
        run: echo "Kubectl apply"
