name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.1.2
      - name: Autenticando no Docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: "Construção da imagem Docher"
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tag: |
            brunoangst/newskube:latest
            brunoangst/newskube:${(github.run_number)}            
      - name: "Publicar a imagem no Docher Hub"
        run: echo "Docker push"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: "Conectar com o Kubernetes"
        run: echo "Configuração do Kubeconfig"
      - name: "Executar o deploy"
        run: echo "Kubectl apply"
